### ISSUE TITLE
bad jsonpath return value handling

### ISSUE THREAD

**Issue by PierreJeanjacquot** [iExecBlockchainComputing/generic-oracle-dapp#5]
`jsonpath.query()` returns an array
https://github.com/iExecBlockchainComputing/generic-oracle-dapp/blob/6dd6bb806fbeac59dec109b15a1705c37c1e781f/src/app.js#L85
so this will always throw
https://github.com/iExecBlockchainComputing/generic-oracle-dapp/blob/6dd6bb806fbeac59dec109b15a1705c37c1e781f/src/app.js#L87

**Comment by rb-iexec** [comment]
Fixed by [989b693](https://github.com/iExecBlockchainComputing/generic-oracle-dapp/commit/989b693e492da8c5c315948c3badba0a6de8acb7)
